# Form implementation generated from reading ui file 'd:\ISAN Security Gizmo Box\backup\Dict_attack.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 700)
        Form.setStyleSheet("background-color: rgba(9,36,43,255)")
        self.name_Label2 = QtWidgets.QLabel(parent=Form)
        self.name_Label2.setGeometry(QtCore.QRect(370, 50, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.name_Label2.setFont(font)
        self.name_Label2.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_Label2.setObjectName("name_Label2")
        self.logo_Label = QtWidgets.QLabel(parent=Form)
        self.logo_Label.setGeometry(QtCore.QRect(40, 50, 91, 81))
        self.logo_Label.setText("")
        self.logo_Label.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\backup\\../../../Downloads/icons8-stan-marsh-96.png"))
        self.logo_Label.setScaledContents(True)
        self.logo_Label.setObjectName("logo_Label")
        self.name_label1 = QtWidgets.QLabel(parent=Form)
        self.name_label1.setGeometry(QtCore.QRect(170, 50, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.name_label1.setFont(font)
        self.name_label1.setStyleSheet("color:rgba(80,218,107,255);")
        self.name_label1.setObjectName("name_label1")
        self.input_LineEdit = QtWidgets.QLineEdit(parent=Form)
        self.input_LineEdit.setGeometry(QtCore.QRect(30, 190, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        self.input_LineEdit.setFont(font)
        self.input_LineEdit.setStyleSheet("border: 5px solid rgba(80,218,107,255);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"")
        self.input_LineEdit.setText("")
        self.input_LineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_LineEdit.setObjectName("input_LineEdit")
        self.back_Button = QtWidgets.QPushButton(parent=Form)
        self.back_Button.setGeometry(QtCore.QRect(30, 650, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.back_Button.setFont(font)
        self.back_Button.setStyleSheet("border: 2px solid white;\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.back_Button.setObjectName("back_Button")
        self.bg_Label = QtWidgets.QLabel(parent=Form)
        self.bg_Label.setGeometry(QtCore.QRect(660, 190, 471, 431))
        self.bg_Label.setStyleSheet("background-color: rgba(27,79,96,70%);\n"
"color: rgb(0, 0, 0);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"")
        self.bg_Label.setText("")
        self.bg_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bg_Label.setObjectName("bg_Label")
        self.start_Button = QtWidgets.QPushButton(parent=Form)
        self.start_Button.setGeometry(QtCore.QRect(560, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_Button.setFont(font)
        self.start_Button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"\n"
"")
        self.start_Button.setObjectName("start_Button")
        self.options_LineEdit = QtWidgets.QLineEdit(parent=Form)
        self.options_LineEdit.setGeometry(QtCore.QRect(30, 250, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        self.options_LineEdit.setFont(font)
        self.options_LineEdit.setStyleSheet("border: 5px solid rgba(80,218,107,255);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"")
        self.options_LineEdit.setText("")
        self.options_LineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.options_LineEdit.setObjectName("options_LineEdit")
        self.clear_Button = QtWidgets.QPushButton(parent=Form)
        self.clear_Button.setGeometry(QtCore.QRect(560, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clear_Button.setFont(font)
        self.clear_Button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"\n"
"")
        self.clear_Button.setObjectName("clear_Button")
        self.progressBar = QtWidgets.QProgressBar(parent=Form)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(30, 320, 541, 31))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.Result_Label = QtWidgets.QLabel(parent=Form)
        self.Result_Label.setGeometry(QtCore.QRect(670, 200, 451, 411))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.Result_Label.setFont(font)
        self.Result_Label.setStyleSheet("color:rgba(240,50,57,255);\n"
"background-color: rgba( 255, 255, 255, 0% );")
        self.Result_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.Result_Label.setObjectName("Result_Label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_Label2.setText(_translate("Form", "Attack"))
        self.name_label1.setText(_translate("Form", "Dictionary"))
        self.input_LineEdit.setPlaceholderText(_translate("Form", "Enter your password"))
        self.back_Button.setText(_translate("Form", "BACK"))
        self.start_Button.setText(_translate("Form", "Start"))
        self.options_LineEdit.setPlaceholderText(_translate("Form", "Options"))
        self.clear_Button.setText(_translate("Form", "CLEAR"))
        self.Result_Label.setText(_translate("Form", "Result"))
