# Form implementation generated from reading ui file 'd:\ISAN Security Gizmo Box\backup\HTTPS_Testing.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 700)
        Form.setStyleSheet("background-color: rgba(9,36,43,255)")
        self.logo = QtWidgets.QLabel(parent=Form)
        self.logo.setGeometry(QtCore.QRect(50, 0, 111, 91))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\backup\\../Logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.name_label1 = QtWidgets.QLabel(parent=Form)
        self.name_label1.setGeometry(QtCore.QRect(170, 30, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.name_label1.setFont(font)
        self.name_label1.setStyleSheet("color:rgba(80,218,107,255);")
        self.name_label1.setObjectName("name_label1")
        self.name_Label2 = QtWidgets.QLabel(parent=Form)
        self.name_Label2.setGeometry(QtCore.QRect(290, 30, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.name_Label2.setFont(font)
        self.name_Label2.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_Label2.setObjectName("name_Label2")
        self.scan_Button = QtWidgets.QPushButton(parent=Form)
        self.scan_Button.setGeometry(QtCore.QRect(540, 200, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.scan_Button.setFont(font)
        self.scan_Button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"\n"
"")
        self.scan_Button.setObjectName("scan_Button")
        self.input_Text = QtWidgets.QLineEdit(parent=Form)
        self.input_Text.setGeometry(QtCore.QRect(30, 200, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        self.input_Text.setFont(font)
        self.input_Text.setStyleSheet("border: 5px solid rgba(80,218,107,255);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"")
        self.input_Text.setText("")
        self.input_Text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_Text.setObjectName("input_Text")
        self.target_Label = QtWidgets.QLabel(parent=Form)
        self.target_Label.setGeometry(QtCore.QRect(270, 140, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.target_Label.setFont(font)
        self.target_Label.setStyleSheet("color: rgb(255, 255, 255);")
        self.target_Label.setObjectName("target_Label")
        self.input_mail = QtWidgets.QLineEdit(parent=Form)
        self.input_mail.setGeometry(QtCore.QRect(570, 620, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        self.input_mail.setFont(font)
        self.input_mail.setStyleSheet("border: 5px solid rgba(80,218,107,255);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"")
        self.input_mail.setText("")
        self.input_mail.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_mail.setObjectName("input_mail")
        self.send_Button = QtWidgets.QPushButton(parent=Form)
        self.send_Button.setGeometry(QtCore.QRect(1080, 620, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.send_Button.setFont(font)
        self.send_Button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"\n"
"")
        self.send_Button.setObjectName("send_Button")
        self.send_label = QtWidgets.QLabel(parent=Form)
        self.send_label.setGeometry(QtCore.QRect(360, 630, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.send_label.setFont(font)
        self.send_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.send_label.setObjectName("send_label")
        self.back_Button = QtWidgets.QPushButton(parent=Form)
        self.back_Button.setGeometry(QtCore.QRect(30, 640, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.back_Button.setFont(font)
        self.back_Button.setStyleSheet("border: 2px solid white;\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.back_Button.setObjectName("back_Button")
        self.output_Label = QtWidgets.QLabel(parent=Form)
        self.output_Label.setGeometry(QtCore.QRect(640, 90, 541, 511))
        self.output_Label.setStyleSheet("background-color: rgba(27,79,96,70%);\n"
"color: rgb(0, 0, 0);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"")
        self.output_Label.setText("")
        self.output_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_Label.setObjectName("output_Label")
        self.output_summary_Label = QtWidgets.QLabel(parent=Form)
        self.output_summary_Label.setGeometry(QtCore.QRect(30, 320, 591, 271))
        self.output_summary_Label.setStyleSheet("background-color: rgba(27,79,96,70%);\n"
"color: rgb(0, 0, 0);\n"
"border-top-left-radius :20px;\n"
"border-top-right-radius :20px; \n"
"border-bottom-left-radius : 20px; \n"
"border-bottom-right-radius : 20px;\n"
"\n"
"")
        self.output_summary_Label.setText("")
        self.output_summary_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_summary_Label.setObjectName("output_summary_Label")
        self.HSTS_Label = QtWidgets.QLabel(parent=Form)
        self.HSTS_Label.setGeometry(QtCore.QRect(60, 370, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.HSTS_Label.setFont(font)
        self.HSTS_Label.setStyleSheet("color:rgba(80,218,107,255);\n"
"background-color: rgba( 255, 255, 255, 0% );")
        self.HSTS_Label.setObjectName("HSTS_Label")
        self.HSTS_Result = QtWidgets.QLabel(parent=Form)
        self.HSTS_Result.setGeometry(QtCore.QRect(200, 370, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        self.HSTS_Result.setFont(font)
        self.HSTS_Result.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color: rgb(255, 255, 255);")
        self.HSTS_Result.setObjectName("HSTS_Result")
        self.warning_Label = QtWidgets.QLabel(parent=Form)
        self.warning_Label.setGeometry(QtCore.QRect(100, 280, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.warning_Label.setFont(font)
        self.warning_Label.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color:rgba(255,89,41,255);")
        self.warning_Label.setText("")
        self.warning_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_Label.setObjectName("warning_Label")
        self.warning_mail = QtWidgets.QLabel(parent=Form)
        self.warning_mail.setGeometry(QtCore.QRect(590, 670, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.warning_mail.setFont(font)
        self.warning_mail.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color:rgba(255,89,41,255);")
        self.warning_mail.setText("")
        self.warning_mail.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_mail.setObjectName("warning_mail")
        self.vulner_Label = QtWidgets.QLabel(parent=Form)
        self.vulner_Label.setGeometry(QtCore.QRect(660, 320, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(19)
        self.vulner_Label.setFont(font)
        self.vulner_Label.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color:rgba(80,218,107,255);")
        self.vulner_Label.setObjectName("vulner_Label")
        self.cer_Label = QtWidgets.QLabel(parent=Form)
        self.cer_Label.setGeometry(QtCore.QRect(650, 140, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(19)
        self.cer_Label.setFont(font)
        self.cer_Label.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color:rgba(80,218,107,255);")
        self.cer_Label.setObjectName("cer_Label")
        self.protocol_Label = QtWidgets.QLabel(parent=Form)
        self.protocol_Label.setGeometry(QtCore.QRect(60, 440, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.protocol_Label.setFont(font)
        self.protocol_Label.setStyleSheet("color:rgba(80,218,107,255);\n"
"background-color: rgba( 255, 255, 255, 0% );")
        self.protocol_Label.setObjectName("protocol_Label")
        self.protocol_Result = QtWidgets.QLabel(parent=Form)
        self.protocol_Result.setGeometry(QtCore.QRect(250, 440, 351, 141))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        self.protocol_Result.setFont(font)
        self.protocol_Result.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color: rgb(255, 255, 255);")
        self.protocol_Result.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.protocol_Result.setObjectName("protocol_Result")
        self.Cer_Result = QtWidgets.QLabel(parent=Form)
        self.Cer_Result.setGeometry(QtCore.QRect(780, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        self.Cer_Result.setFont(font)
        self.Cer_Result.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color: rgb(255, 255, 255);")
        self.Cer_Result.setObjectName("Cer_Result")
        self.vulner_Result = QtWidgets.QLabel(parent=Form)
        self.vulner_Result.setGeometry(QtCore.QRect(860, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        self.vulner_Result.setFont(font)
        self.vulner_Result.setStyleSheet("background-color: rgba( 255, 255, 255, 0% );\n"
"color: rgb(255, 255, 255);")
        self.vulner_Result.setObjectName("vulner_Result")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label1.setText(_translate("Form", "HTTPS"))
        self.name_Label2.setText(_translate("Form", "TESTING"))
        self.scan_Button.setText(_translate("Form", "SCAN"))
        self.input_Text.setPlaceholderText(_translate("Form", "Enter a URL"))
        self.target_Label.setText(_translate("Form", "TARGET"))
        self.input_mail.setPlaceholderText(_translate("Form", "Enter e-mail"))
        self.send_Button.setText(_translate("Form", "SEND"))
        self.send_label.setText(_translate("Form", "SEND FULL REPORT TO E-MAIL"))
        self.back_Button.setText(_translate("Form", "BACK"))
        self.HSTS_Label.setText(_translate("Form", "HSTS Preload:"))
        self.HSTS_Result.setText(_translate("Form", "--"))
        self.vulner_Label.setText(_translate("Form", "Testing Vulneravility:"))
        self.cer_Label.setText(_translate("Form", "Certificate:"))
        self.protocol_Label.setText(_translate("Form", "Testing Protocol:"))
        self.protocol_Result.setText(_translate("Form", "--"))
        self.Cer_Result.setText(_translate("Form", "--"))
        self.vulner_Result.setText(_translate("Form", "--"))
