# Form implementation generated from reading ui file 'd:\ISAN Security Gizmo Box\assets\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1374, 738)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_main = QtWidgets.QWidget(parent=Form)
        self.widget_main.setGeometry(QtCore.QRect(0, 0, 1381, 751))
        self.widget_main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_main.setObjectName("widget_main")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_main)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 10, 1361, 721))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.labe_isanSec = QtWidgets.QLabel(parent=self.page_home)
        self.labe_isanSec.setGeometry(QtCore.QRect(330, 150, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labe_isanSec.setFont(font)
        self.labe_isanSec.setStyleSheet("color: rgb(42, 49, 66);")
        self.labe_isanSec.setObjectName("labe_isanSec")
        self.label_description1Home = QtWidgets.QLabel(parent=self.page_home)
        self.label_description1Home.setGeometry(QtCore.QRect(280, 210, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_description1Home.setFont(font)
        self.label_description1Home.setStyleSheet(" color: rgba(122,122,122,255);")
        self.label_description1Home.setObjectName("label_description1Home")
        self.label_description2Home = QtWidgets.QLabel(parent=self.page_home)
        self.label_description2Home.setGeometry(QtCore.QRect(270, 260, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_description2Home.setFont(font)
        self.label_description2Home.setStyleSheet(" color: rgba(122,122,122,255);")
        self.label_description2Home.setObjectName("label_description2Home")
        self.btn_advancedUserHome = QtWidgets.QPushButton(parent=self.page_home)
        self.btn_advancedUserHome.setGeometry(QtCore.QRect(330, 360, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_advancedUserHome.setFont(font)
        self.btn_advancedUserHome.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_advancedUserHome.setObjectName("btn_advancedUserHome")
        self.btn_networkUserHome = QtWidgets.QPushButton(parent=self.page_home)
        self.btn_networkUserHome.setGeometry(QtCore.QRect(530, 360, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_networkUserHome.setFont(font)
        self.btn_networkUserHome.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_networkUserHome.setObjectName("btn_networkUserHome")
        self.label_gizmoHome = QtWidgets.QLabel(parent=self.page_home)
        self.label_gizmoHome.setGeometry(QtCore.QRect(540, 150, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_gizmoHome.setFont(font)
        self.label_gizmoHome.setStyleSheet("color: rgba(0,143,255,255);")
        self.label_gizmoHome.setObjectName("label_gizmoHome")
        self.label_imageHome = QtWidgets.QLabel(parent=self.page_home)
        self.label_imageHome.setGeometry(QtCore.QRect(840, 100, 461, 471))
        self.label_imageHome.setText("")
        self.label_imageHome.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/main.png"))
        self.label_imageHome.setScaledContents(True)
        self.label_imageHome.setObjectName("label_imageHome")
        self.stackedWidget.addWidget(self.page_home)
        self.page_advancedUser = QtWidgets.QWidget()
        self.page_advancedUser.setObjectName("page_advancedUser")
        self.btn_password = QtWidgets.QPushButton(parent=self.page_advancedUser)
        self.btn_password.setGeometry(QtCore.QRect(360, 350, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_password.setFont(font)
        self.btn_password.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_password.setObjectName("btn_password")
        self.btn_malware = QtWidgets.QPushButton(parent=self.page_advancedUser)
        self.btn_malware.setGeometry(QtCore.QRect(630, 350, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_malware.setFont(font)
        self.btn_malware.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_malware.setObjectName("btn_malware")
        self.btn_digest = QtWidgets.QPushButton(parent=self.page_advancedUser)
        self.btn_digest.setGeometry(QtCore.QRect(860, 350, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_digest.setFont(font)
        self.btn_digest.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_digest.setObjectName("btn_digest")
        self.label_isanSec_adupage = QtWidgets.QLabel(parent=self.page_advancedUser)
        self.label_isanSec_adupage.setGeometry(QtCore.QRect(530, 140, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_isanSec_adupage.setFont(font)
        self.label_isanSec_adupage.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_isanSec_adupage.setObjectName("label_isanSec_adupage")
        self.label_advancdUser = QtWidgets.QLabel(parent=self.page_advancedUser)
        self.label_advancdUser.setGeometry(QtCore.QRect(560, 190, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_advancdUser.setFont(font)
        self.label_advancdUser.setStyleSheet("color: rgba(0,143,255,255);")
        self.label_advancdUser.setObjectName("label_advancdUser")
        self.label_description_adupage = QtWidgets.QLabel(parent=self.page_advancedUser)
        self.label_description_adupage.setGeometry(QtCore.QRect(370, 240, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_description_adupage.setFont(font)
        self.label_description_adupage.setStyleSheet(" color: rgba(122,122,122,255);")
        self.label_description_adupage.setObjectName("label_description_adupage")
        self.label_image_key = QtWidgets.QLabel(parent=self.page_advancedUser)
        self.label_image_key.setGeometry(QtCore.QRect(230, 30, 231, 211))
        self.label_image_key.setText("")
        self.label_image_key.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/key.png"))
        self.label_image_key.setScaledContents(True)
        self.label_image_key.setObjectName("label_image_key")
        self.label_image_msg = QtWidgets.QLabel(parent=self.page_advancedUser)
        self.label_image_msg.setGeometry(QtCore.QRect(870, 400, 261, 251))
        self.label_image_msg.setText("")
        self.label_image_msg.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/message.png"))
        self.label_image_msg.setScaledContents(True)
        self.label_image_msg.setObjectName("label_image_msg")
        self.label_image_bug = QtWidgets.QLabel(parent=self.page_advancedUser)
        self.label_image_bug.setGeometry(QtCore.QRect(1020, 0, 261, 251))
        self.label_image_bug.setText("")
        self.label_image_bug.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/bug.png"))
        self.label_image_bug.setScaledContents(True)
        self.label_image_bug.setObjectName("label_image_bug")
        self.label_image_star_adupage = QtWidgets.QLabel(parent=self.page_advancedUser)
        self.label_image_star_adupage.setGeometry(QtCore.QRect(310, 500, 111, 111))
        self.label_image_star_adupage.setText("")
        self.label_image_star_adupage.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/star.png"))
        self.label_image_star_adupage.setScaledContents(True)
        self.label_image_star_adupage.setObjectName("label_image_star_adupage")
        self.stackedWidget.addWidget(self.page_advancedUser)
        self.page_password = QtWidgets.QWidget()
        self.page_password.setObjectName("page_password")
        self.lineEdit_inputPwd = QtWidgets.QLineEdit(parent=self.page_password)
        self.lineEdit_inputPwd.setGeometry(QtCore.QRect(350, 130, 811, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_inputPwd.setFont(font)
        self.lineEdit_inputPwd.setStyleSheet("QLineEdit {\n"
"  border: 1px solid gray;\n"
"  color: rgba(40,43,61,255);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid;\n"
"  border-color: rgba(0,143,255,255);\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid;\n"
"  border-color: rgba(88,199,141,255);\n"
"}\n"
"")
        self.lineEdit_inputPwd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_inputPwd.setObjectName("lineEdit_inputPwd")
        self.label_pwd = QtWidgets.QLabel(parent=self.page_password)
        self.label_pwd.setGeometry(QtCore.QRect(600, 50, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_pwd.setFont(font)
        self.label_pwd.setStyleSheet("color: rgb(38, 50, 56);")
        self.label_pwd.setObjectName("label_pwd")
        self.widget_specialWarning = QtWidgets.QWidget(parent=self.page_password)
        self.widget_specialWarning.setGeometry(QtCore.QRect(930, 260, 381, 371))
        self.widget_specialWarning.setStyleSheet("background-color:rgba(242,243,245,255);\n"
"border-radius: 5px;")
        self.widget_specialWarning.setObjectName("widget_specialWarning")
        self.label_title_specialWarning = QtWidgets.QLabel(parent=self.widget_specialWarning)
        self.label_title_specialWarning.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_specialWarning.setFont(font)
        self.label_title_specialWarning.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_title_specialWarning.setObjectName("label_title_specialWarning")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget_specialWarning)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 321, 292))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(50)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.checkDigits = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkDigits.setFont(font)
        self.checkDigits.setStyleSheet("QCheckBox::indicator{\n"
"     width: 0; height 0;\n"
"    border-radius: 10px;\n"
"}")
        self.checkDigits.setObjectName("checkDigits")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkDigits)
        self.checkLower = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkLower.setFont(font)
        self.checkLower.setStyleSheet("QCheckBox::indicator{\n"
"     width: 0; height 0;\n"
"    border-radius: 10px;\n"
"}")
        self.checkLower.setObjectName("checkLower")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkLower)
        self.checkUpper = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkUpper.setFont(font)
        self.checkUpper.setStyleSheet("QCheckBox::indicator{\n"
"     width: 0; height 0;\n"
"    border-radius: 10px;\n"
"}")
        self.checkUpper.setObjectName("checkUpper")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkUpper)
        self.checkSpecial = QtWidgets.QCheckBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkSpecial.setFont(font)
        self.checkSpecial.setStyleSheet("QCheckBox::indicator{\n"
"     width: 0; height 0;\n"
"    border-radius: 10px;\n"
"}")
        self.checkSpecial.setObjectName("checkSpecial")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkSpecial)
        self.checkLength = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.checkLength.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.checkLength.setFont(font)
        self.checkLength.setAcceptDrops(False)
        self.checkLength.setAutoFillBackground(False)
        self.checkLength.setStyleSheet("QCheckBox::indicator{\n"
"     width: 0; height 0;\n"
"    border-radius: 10px;\n"
"}")
        self.checkLength.setCheckable(True)
        self.checkLength.setChecked(False)
        self.checkLength.setAutoRepeat(False)
        self.checkLength.setAutoExclusive(False)
        self.checkLength.setTristate(False)
        self.checkLength.setObjectName("checkLength")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkLength)
        self.widget_outputPwd = QtWidgets.QWidget(parent=self.page_password)
        self.widget_outputPwd.setGeometry(QtCore.QRect(240, 260, 661, 371))
        self.widget_outputPwd.setStyleSheet("background-color:rgba(242,243,245,255);\n"
"border-radius: 5px;")
        self.widget_outputPwd.setObjectName("widget_outputPwd")
        self.label_pwdStrength = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_pwdStrength.setGeometry(QtCore.QRect(10, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_pwdStrength.setFont(font)
        self.label_pwdStrength.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_pwdStrength.setObjectName("label_pwdStrength")
        self.label_timetocrack = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_timetocrack.setGeometry(QtCore.QRect(10, 70, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_timetocrack.setFont(font)
        self.label_timetocrack.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_timetocrack.setObjectName("label_timetocrack")
        self.label_entropy = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_entropy.setGeometry(QtCore.QRect(10, 120, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_entropy.setFont(font)
        self.label_entropy.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_entropy.setObjectName("label_entropy")
        self.tbtn_info_pwd = QtWidgets.QToolButton(parent=self.widget_outputPwd)
        self.tbtn_info_pwd.setGeometry(QtCore.QRect(230, 120, 21, 21))
        self.tbtn_info_pwd.setStyleSheet(" QToolButton{\n"
"        border-radius: 5px;\n"
"        background-color: transparent; \n"
"    }\n"
"")
        self.tbtn_info_pwd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_info.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbtn_info_pwd.setIcon(icon)
        self.tbtn_info_pwd.setObjectName("tbtn_info_pwd")
        self.label_chkNordpass = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_chkNordpass.setGeometry(QtCore.QRect(190, 180, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_chkNordpass.setFont(font)
        self.label_chkNordpass.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_chkNordpass.setObjectName("label_chkNordpass")
        self.btn_dicattack = QtWidgets.QPushButton(parent=self.widget_outputPwd)
        self.btn_dicattack.setGeometry(QtCore.QRect(450, 320, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dicattack.setFont(font)
        self.btn_dicattack.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_dicattack.setObjectName("btn_dicattack")
        self.label_outStrengthPwd = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_outStrengthPwd.setGeometry(QtCore.QRect(360, 30, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_outStrengthPwd.setFont(font)
        self.label_outStrengthPwd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_outStrengthPwd.setObjectName("label_outStrengthPwd")
        self.label_outTimeCrackPwd = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_outTimeCrackPwd.setGeometry(QtCore.QRect(360, 70, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_outTimeCrackPwd.setFont(font)
        self.label_outTimeCrackPwd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_outTimeCrackPwd.setObjectName("label_outTimeCrackPwd")
        self.label_outEntropyPwd = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_outEntropyPwd.setGeometry(QtCore.QRect(360, 110, 270, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_outEntropyPwd.setFont(font)
        self.label_outEntropyPwd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_outEntropyPwd.setObjectName("label_outEntropyPwd")
        self.label_outChkNordpass = QtWidgets.QLabel(parent=self.widget_outputPwd)
        self.label_outChkNordpass.setGeometry(QtCore.QRect(40, 250, 571, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_outChkNordpass.setFont(font)
        self.label_outChkNordpass.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_outChkNordpass.setObjectName("label_outChkNordpass")
        self.label_textPwd = QtWidgets.QLabel(parent=self.page_password)
        self.label_textPwd.setGeometry(QtCore.QRect(870, 190, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_textPwd.setFont(font)
        self.label_textPwd.setStyleSheet("color: rgb(208, 208, 208);")
        self.label_textPwd.setObjectName("label_textPwd")
        self.tbtn_eyePwd = QtWidgets.QToolButton(parent=self.page_password)
        self.tbtn_eyePwd.setGeometry(QtCore.QRect(1120, 140, 31, 22))
        self.tbtn_eyePwd.setStyleSheet(" QToolButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.tbtn_eyePwd.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_openeye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbtn_eyePwd.setIcon(icon1)
        self.tbtn_eyePwd.setIconSize(QtCore.QSize(30, 30))
        self.tbtn_eyePwd.setObjectName("tbtn_eyePwd")
        self.btn_backPwd = QtWidgets.QPushButton(parent=self.page_password)
        self.btn_backPwd.setGeometry(QtCore.QRect(200, 30, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_backPwd.setFont(font)
        self.btn_backPwd.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backPwd.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_back.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_backPwd.setIcon(icon2)
        self.btn_backPwd.setIconSize(QtCore.QSize(30, 30))
        self.btn_backPwd.setObjectName("btn_backPwd")
        self.widget_outputPwd.raise_()
        self.lineEdit_inputPwd.raise_()
        self.label_pwd.raise_()
        self.widget_specialWarning.raise_()
        self.label_textPwd.raise_()
        self.tbtn_eyePwd.raise_()
        self.btn_backPwd.raise_()
        self.stackedWidget.addWidget(self.page_password)
        self.page_dictionary = QtWidgets.QWidget()
        self.page_dictionary.setObjectName("page_dictionary")
        self.label_dictionary = QtWidgets.QLabel(parent=self.page_dictionary)
        self.label_dictionary.setGeometry(QtCore.QRect(600, 50, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_dictionary.setFont(font)
        self.label_dictionary.setStyleSheet("color: rgb(38, 50, 56);")
        self.label_dictionary.setObjectName("label_dictionary")
        self.lineEdit_inputDic = QtWidgets.QLineEdit(parent=self.page_dictionary)
        self.lineEdit_inputDic.setGeometry(QtCore.QRect(340, 130, 811, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_inputDic.setFont(font)
        self.lineEdit_inputDic.setStyleSheet("QLineEdit {\n"
"  border: 1px solid gray;\n"
"  color: rgba(40,43,61,255);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid;\n"
"  border-color: rgba(0,143,255,255);\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid;\n"
"  border-color: rgba(88,199,141,255);\n"
"}\n"
"")
        self.lineEdit_inputDic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_inputDic.setObjectName("lineEdit_inputDic")
        self.label_textPwd2 = QtWidgets.QLabel(parent=self.page_dictionary)
        self.label_textPwd2.setGeometry(QtCore.QRect(910, 190, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_textPwd2.setFont(font)
        self.label_textPwd2.setStyleSheet("color: rgb(208, 208, 208);")
        self.label_textPwd2.setObjectName("label_textPwd2")
        self.widget_outputDic = QtWidgets.QWidget(parent=self.page_dictionary)
        self.widget_outputDic.setGeometry(QtCore.QRect(280, 310, 961, 301))
        self.widget_outputDic.setStyleSheet("background-color:rgba(242,243,245,255);\n"
"border-radius: 5px;")
        self.widget_outputDic.setObjectName("widget_outputDic")
        self.label_outDic = QtWidgets.QLabel(parent=self.widget_outputDic)
        self.label_outDic.setGeometry(QtCore.QRect(30, 20, 911, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_outDic.setFont(font)
        self.label_outDic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_outDic.setObjectName("label_outDic")
        self.btn_openDic = QtWidgets.QPushButton(parent=self.page_dictionary)
        self.btn_openDic.setGeometry(QtCore.QRect(950, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_openDic.setFont(font)
        self.btn_openDic.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_openDic.setIcon(icon3)
        self.btn_openDic.setIconSize(QtCore.QSize(30, 30))
        self.btn_openDic.setObjectName("btn_openDic")
        self.btn_rockyou = QtWidgets.QPushButton(parent=self.page_dictionary)
        self.btn_rockyou.setGeometry(QtCore.QRect(300, 240, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rockyou.setFont(font)
        self.btn_rockyou.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_rockyou.setIconSize(QtCore.QSize(30, 30))
        self.btn_rockyou.setObjectName("btn_rockyou")
        self.btn_crackstation = QtWidgets.QPushButton(parent=self.page_dictionary)
        self.btn_crackstation.setGeometry(QtCore.QRect(490, 240, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_crackstation.setFont(font)
        self.btn_crackstation.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_crackstation.setIconSize(QtCore.QSize(30, 30))
        self.btn_crackstation.setObjectName("btn_crackstation")
        self.lineEdit_inputFileDic = QtWidgets.QLineEdit(parent=self.page_dictionary)
        self.lineEdit_inputFileDic.setGeometry(QtCore.QRect(670, 240, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_inputFileDic.setFont(font)
        self.lineEdit_inputFileDic.setStyleSheet("QLineEdit {\n"
"  border: 1px solid gray;\n"
"  color: rgba(40,43,61,255);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid;\n"
"  border-color: rgba(0,143,255,255);\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid;\n"
"  border-color: rgba(88,199,141,255);\n"
"}\n"
"")
        self.lineEdit_inputFileDic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_inputFileDic.setObjectName("lineEdit_inputFileDic")
        self.btn_clearDic = QtWidgets.QPushButton(parent=self.page_dictionary)
        self.btn_clearDic.setGeometry(QtCore.QRect(1090, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clearDic.setFont(font)
        self.btn_clearDic.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_trash.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_clearDic.setIcon(icon4)
        self.btn_clearDic.setIconSize(QtCore.QSize(30, 30))
        self.btn_clearDic.setObjectName("btn_clearDic")
        self.progressBar = QtWidgets.QProgressBar(parent=self.page_dictionary)
        self.progressBar.setGeometry(QtCore.QRect(280, 630, 961, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid rgb(42, 49, 66);\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar:chunk {\n"
"     border-radius: 10px;\n"
"    background-color:  rgb(42, 49, 66); /* Custom color for the progress bar chunk */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.btn_backDic = QtWidgets.QPushButton(parent=self.page_dictionary)
        self.btn_backDic.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backDic.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backDic.setText("")
        self.btn_backDic.setIcon(icon2)
        self.btn_backDic.setIconSize(QtCore.QSize(30, 30))
        self.btn_backDic.setObjectName("btn_backDic")
        self.tbtn_eyeDic = QtWidgets.QToolButton(parent=self.page_dictionary)
        self.tbtn_eyeDic.setGeometry(QtCore.QRect(1100, 140, 31, 22))
        self.tbtn_eyeDic.setStyleSheet(" QToolButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.tbtn_eyeDic.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icon_openeye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbtn_eyeDic.setIcon(icon5)
        self.tbtn_eyeDic.setIconSize(QtCore.QSize(30, 30))
        self.tbtn_eyeDic.setObjectName("tbtn_eyeDic")
        self.stackedWidget.addWidget(self.page_dictionary)
        self.page_malware = QtWidgets.QWidget()
        self.page_malware.setObjectName("page_malware")
        self.label_malware = QtWidgets.QLabel(parent=self.page_malware)
        self.label_malware.setGeometry(QtCore.QRect(600, 50, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_malware.setFont(font)
        self.label_malware.setStyleSheet("color: rgb(38, 50, 56);")
        self.label_malware.setObjectName("label_malware")
        self.lineEdit_inputMalware = QtWidgets.QLineEdit(parent=self.page_malware)
        self.lineEdit_inputMalware.setGeometry(QtCore.QRect(370, 130, 811, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_inputMalware.setFont(font)
        self.lineEdit_inputMalware.setStyleSheet("QLineEdit {\n"
"  border: 1px solid gray;\n"
"  color: rgba(40,43,61,255);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid;\n"
"  border-color: rgba(0,143,255,255);\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid;\n"
"  border-color: rgba(88,199,141,255);\n"
"}\n"
"")
        self.lineEdit_inputMalware.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_inputMalware.setObjectName("lineEdit_inputMalware")
        self.widget_output_malware = QtWidgets.QWidget(parent=self.page_malware)
        self.widget_output_malware.setGeometry(QtCore.QRect(300, 250, 931, 371))
        self.widget_output_malware.setStyleSheet("background-color:rgba(242,243,245,255);\n"
"border-radius: 5px;")
        self.widget_output_malware.setObjectName("widget_output_malware")
        self.label_nameMalware = QtWidgets.QLabel(parent=self.widget_output_malware)
        self.label_nameMalware.setGeometry(QtCore.QRect(40, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_nameMalware.setFont(font)
        self.label_nameMalware.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_nameMalware.setObjectName("label_nameMalware")
        self.label_sizeMalware = QtWidgets.QLabel(parent=self.widget_output_malware)
        self.label_sizeMalware.setGeometry(QtCore.QRect(40, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_sizeMalware.setFont(font)
        self.label_sizeMalware.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_sizeMalware.setObjectName("label_sizeMalware")
        self.label_dateMalware = QtWidgets.QLabel(parent=self.widget_output_malware)
        self.label_dateMalware.setGeometry(QtCore.QRect(40, 130, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_dateMalware.setFont(font)
        self.label_dateMalware.setStyleSheet("color: rgb(42, 49, 66);\n"
" background-color: transparent; \n"
"   \n"
"")
        self.label_dateMalware.setObjectName("label_dateMalware")
        self.label_typeMalware = QtWidgets.QLabel(parent=self.widget_output_malware)
        self.label_typeMalware.setGeometry(QtCore.QRect(40, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_typeMalware.setFont(font)
        self.label_typeMalware.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_typeMalware.setObjectName("label_typeMalware")
        self.btn_moreMalware = QtWidgets.QPushButton(parent=self.widget_output_malware)
        self.btn_moreMalware.setGeometry(QtCore.QRect(770, 320, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_moreMalware.setFont(font)
        self.btn_moreMalware.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_more.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_moreMalware.setIcon(icon6)
        self.btn_moreMalware.setIconSize(QtCore.QSize(30, 30))
        self.btn_moreMalware.setObjectName("btn_moreMalware")
        self.btn_clearMalware = QtWidgets.QPushButton(parent=self.page_malware)
        self.btn_clearMalware.setGeometry(QtCore.QRect(690, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clearMalware.setFont(font)
        self.btn_clearMalware.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_clearMalware.setIcon(icon4)
        self.btn_clearMalware.setIconSize(QtCore.QSize(30, 30))
        self.btn_clearMalware.setObjectName("btn_clearMalware")
        self.btn_scanMalware = QtWidgets.QPushButton(parent=self.page_malware)
        self.btn_scanMalware.setGeometry(QtCore.QRect(860, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_scanMalware.setFont(font)
        self.btn_scanMalware.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_scan.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_scanMalware.setIcon(icon7)
        self.btn_scanMalware.setIconSize(QtCore.QSize(30, 30))
        self.btn_scanMalware.setObjectName("btn_scanMalware")
        self.btn_openMalware = QtWidgets.QPushButton(parent=self.page_malware)
        self.btn_openMalware.setGeometry(QtCore.QRect(520, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_openMalware.setFont(font)
        self.btn_openMalware.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_openMalware.setIcon(icon3)
        self.btn_openMalware.setIconSize(QtCore.QSize(30, 30))
        self.btn_openMalware.setObjectName("btn_openMalware")
        self.btn_backMalware = QtWidgets.QPushButton(parent=self.page_malware)
        self.btn_backMalware.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backMalware.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backMalware.setText("")
        self.btn_backMalware.setIcon(icon2)
        self.btn_backMalware.setIconSize(QtCore.QSize(30, 30))
        self.btn_backMalware.setObjectName("btn_backMalware")
        self.stackedWidget.addWidget(self.page_malware)
        self.page_detailMalware = QtWidgets.QWidget()
        self.page_detailMalware.setObjectName("page_detailMalware")
        self.label_5 = QtWidgets.QLabel(parent=self.page_detailMalware)
        self.label_5.setGeometry(QtCore.QRect(660, 250, 141, 61))
        self.label_5.setObjectName("label_5")
        self.btn_backDetailMalware = QtWidgets.QPushButton(parent=self.page_detailMalware)
        self.btn_backDetailMalware.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backDetailMalware.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backDetailMalware.setText("")
        self.btn_backDetailMalware.setIcon(icon2)
        self.btn_backDetailMalware.setIconSize(QtCore.QSize(30, 30))
        self.btn_backDetailMalware.setObjectName("btn_backDetailMalware")
        self.stackedWidget.addWidget(self.page_detailMalware)
        self.page_digest = QtWidgets.QWidget()
        self.page_digest.setObjectName("page_digest")
        self.label_digest = QtWidgets.QLabel(parent=self.page_digest)
        self.label_digest.setGeometry(QtCore.QRect(600, 50, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_digest.setFont(font)
        self.label_digest.setStyleSheet("color: rgb(38, 50, 56);")
        self.label_digest.setObjectName("label_digest")
        self.lineEdit_inputDigest = QtWidgets.QLineEdit(parent=self.page_digest)
        self.lineEdit_inputDigest.setGeometry(QtCore.QRect(370, 110, 811, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_inputDigest.setFont(font)
        self.lineEdit_inputDigest.setStyleSheet("QLineEdit {\n"
"  border: 1px solid gray;\n"
"  color: rgba(40,43,61,255);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid;\n"
"  border-color: rgba(0,143,255,255);\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid;\n"
"  border-color: rgba(88,199,141,255);\n"
"}\n"
"")
        self.lineEdit_inputDigest.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_inputDigest.setObjectName("lineEdit_inputDigest")
        self.btn_openDigest = QtWidgets.QPushButton(parent=self.page_digest)
        self.btn_openDigest.setGeometry(QtCore.QRect(630, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_openDigest.setFont(font)
        self.btn_openDigest.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_openDigest.setIcon(icon3)
        self.btn_openDigest.setIconSize(QtCore.QSize(30, 30))
        self.btn_openDigest.setObjectName("btn_openDigest")
        self.btn_clearDigest = QtWidgets.QPushButton(parent=self.page_digest)
        self.btn_clearDigest.setGeometry(QtCore.QRect(800, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clearDigest.setFont(font)
        self.btn_clearDigest.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_clearDigest.setIcon(icon4)
        self.btn_clearDigest.setIconSize(QtCore.QSize(30, 30))
        self.btn_clearDigest.setObjectName("btn_clearDigest")
        self.comboBox_sha2 = QtWidgets.QComboBox(parent=self.page_digest)
        self.comboBox_sha2.setGeometry(QtCore.QRect(760, 260, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_sha2.setFont(font)
        self.comboBox_sha2.setStyleSheet("QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 5px;\n"
"        padding: 1px 18px 1px 3px;\n"
"        min-width: 6em;\n"
"\n"
"\n"
" }\n"
" QComboBox:drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"}\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons/Icon_down.png);\n"
"}\n"
"QComboBox:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"\n"
"")
        self.comboBox_sha2.setIconSize(QtCore.QSize(10, 10))
        self.comboBox_sha2.setObjectName("comboBox_sha2")
        self.comboBox_sha2.addItem("")
        self.comboBox_sha2.addItem("")
        self.comboBox_sha2.addItem("")
        self.comboBox_sha2.addItem("")
        self.comboBox_sha2.addItem("")
        self.comboBox_sha2.addItem("")
        self.comboBox_sha2.setItemText(5, "")
        self.btn_md5 = QtWidgets.QPushButton(parent=self.page_digest)
        self.btn_md5.setGeometry(QtCore.QRect(460, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_md5.setFont(font)
        self.btn_md5.setStyleSheet("QPushButton{\n"
"         border: 1px solid gray;\n"
"          color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"QPushButton:focus {\n"
"  border: 1px solid;\n"
"  border-color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_md5.setObjectName("btn_md5")
        self.btn_sha1 = QtWidgets.QPushButton(parent=self.page_digest)
        self.btn_sha1.setGeometry(QtCore.QRect(610, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sha1.setFont(font)
        self.btn_sha1.setStyleSheet("QPushButton{\n"
"         border: 1px solid gray;\n"
"          color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"QPushButton:focus {\n"
"  border: 1px solid;\n"
"  border-color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_sha1.setObjectName("btn_sha1")
        self.comboBox_sha3 = QtWidgets.QComboBox(parent=self.page_digest)
        self.comboBox_sha3.setGeometry(QtCore.QRect(930, 260, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_sha3.setFont(font)
        self.comboBox_sha3.setStyleSheet("QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 5px;\n"
"        padding: 1px 18px 1px 3px;\n"
"        min-width: 6em;\n"
"\n"
" }\n"
" QComboBox:drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"}\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons/Icon_down.png);\n"
"}\n"
"QComboBox:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"\n"
"")
        self.comboBox_sha3.setIconSize(QtCore.QSize(10, 10))
        self.comboBox_sha3.setObjectName("comboBox_sha3")
        self.comboBox_sha3.addItem("")
        self.comboBox_sha3.addItem("")
        self.comboBox_sha3.addItem("")
        self.comboBox_sha3.addItem("")
        self.comboBox_sha3.addItem("")
        self.comboBox_sha3.addItem("")
        self.comboBox_sha3.setItemText(5, "")
        self.widget_optputDigest = QtWidgets.QWidget(parent=self.page_digest)
        self.widget_optputDigest.setGeometry(QtCore.QRect(280, 320, 981, 311))
        self.widget_optputDigest.setStyleSheet("background-color:rgba(242,243,245,255);\n"
"border-radius: 5px;")
        self.widget_optputDigest.setObjectName("widget_optputDigest")
        self.label_resultDigest = QtWidgets.QLabel(parent=self.widget_optputDigest)
        self.label_resultDigest.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_resultDigest.setFont(font)
        self.label_resultDigest.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_resultDigest.setObjectName("label_resultDigest")
        self.widget_qr = QtWidgets.QWidget(parent=self.widget_optputDigest)
        self.widget_qr.setGeometry(QtCore.QRect(590, 10, 381, 291))
        self.widget_qr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.widget_qr.setObjectName("widget_qr")
        self.btn_saveDigest = QtWidgets.QPushButton(parent=self.widget_qr)
        self.btn_saveDigest.setGeometry(QtCore.QRect(250, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_saveDigest.setFont(font)
        self.btn_saveDigest.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/icon_save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_saveDigest.setIcon(icon8)
        self.btn_saveDigest.setIconSize(QtCore.QSize(30, 30))
        self.btn_saveDigest.setObjectName("btn_saveDigest")
        self.label_outDic_4 = QtWidgets.QLabel(parent=self.widget_qr)
        self.label_outDic_4.setGeometry(QtCore.QRect(40, 30, 311, 191))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_outDic_4.setFont(font)
        self.label_outDic_4.setText("")
        self.label_outDic_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_outDic_4.setObjectName("label_outDic_4")
        self.label_outDic_3 = QtWidgets.QLabel(parent=self.widget_optputDigest)
        self.label_outDic_3.setGeometry(QtCore.QRect(140, 30, 421, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_outDic_3.setFont(font)
        self.label_outDic_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_outDic_3.setObjectName("label_outDic_3")
        self.btn_backDigest = QtWidgets.QPushButton(parent=self.page_digest)
        self.btn_backDigest.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backDigest.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backDigest.setText("")
        self.btn_backDigest.setIcon(icon2)
        self.btn_backDigest.setIconSize(QtCore.QSize(30, 30))
        self.btn_backDigest.setObjectName("btn_backDigest")
        self.stackedWidget.addWidget(self.page_digest)
        self.page_networkUser_home = QtWidgets.QWidget()
        self.page_networkUser_home.setObjectName("page_networkUser_home")
        self.label_isanSec_nwu = QtWidgets.QLabel(parent=self.page_networkUser_home)
        self.label_isanSec_nwu.setGeometry(QtCore.QRect(520, 180, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_isanSec_nwu.setFont(font)
        self.label_isanSec_nwu.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_isanSec_nwu.setObjectName("label_isanSec_nwu")
        self.label_image_firewall = QtWidgets.QLabel(parent=self.page_networkUser_home)
        self.label_image_firewall.setGeometry(QtCore.QRect(220, 30, 231, 211))
        self.label_image_firewall.setText("")
        self.label_image_firewall.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/firewall.png"))
        self.label_image_firewall.setScaledContents(True)
        self.label_image_firewall.setObjectName("label_image_firewall")
        self.btn_vulner = QtWidgets.QPushButton(parent=self.page_networkUser_home)
        self.btn_vulner.setGeometry(QtCore.QRect(500, 390, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_vulner.setFont(font)
        self.btn_vulner.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_vulner.setObjectName("btn_vulner")
        self.label_image_http = QtWidgets.QLabel(parent=self.page_networkUser_home)
        self.label_image_http.setGeometry(QtCore.QRect(1030, 60, 211, 201))
        self.label_image_http.setText("")
        self.label_image_http.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/https.png"))
        self.label_image_http.setScaledContents(True)
        self.label_image_http.setObjectName("label_image_http")
        self.label_networkUser = QtWidgets.QLabel(parent=self.page_networkUser_home)
        self.label_networkUser.setGeometry(QtCore.QRect(570, 230, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_networkUser.setFont(font)
        self.label_networkUser.setStyleSheet("color: rgba(0,143,255,255);")
        self.label_networkUser.setObjectName("label_networkUser")
        self.label_image_correct = QtWidgets.QLabel(parent=self.page_networkUser_home)
        self.label_image_correct.setGeometry(QtCore.QRect(1000, 480, 211, 201))
        self.label_image_correct.setText("")
        self.label_image_correct.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/correct.png"))
        self.label_image_correct.setScaledContents(True)
        self.label_image_correct.setObjectName("label_image_correct")
        self.label_image_star = QtWidgets.QLabel(parent=self.page_networkUser_home)
        self.label_image_star.setGeometry(QtCore.QRect(310, 520, 111, 111))
        self.label_image_star.setText("")
        self.label_image_star.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../images/star.png"))
        self.label_image_star.setScaledContents(True)
        self.label_image_star.setObjectName("label_image_star")
        self.label_description_nwu = QtWidgets.QLabel(parent=self.page_networkUser_home)
        self.label_description_nwu.setGeometry(QtCore.QRect(430, 280, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_description_nwu.setFont(font)
        self.label_description_nwu.setStyleSheet(" color: rgba(122,122,122,255);")
        self.label_description_nwu.setObjectName("label_description_nwu")
        self.btn_https = QtWidgets.QPushButton(parent=self.page_networkUser_home)
        self.btn_https.setGeometry(QtCore.QRect(790, 390, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_https.setFont(font)
        self.btn_https.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_https.setObjectName("btn_https")
        self.stackedWidget.addWidget(self.page_networkUser_home)
        self.page_vulner = QtWidgets.QWidget()
        self.page_vulner.setObjectName("page_vulner")
        self.label_vulner = QtWidgets.QLabel(parent=self.page_vulner)
        self.label_vulner.setGeometry(QtCore.QRect(600, 50, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_vulner.setFont(font)
        self.label_vulner.setStyleSheet("color: rgb(38, 50, 56);")
        self.label_vulner.setObjectName("label_vulner")
        self.btn_openVulner = QtWidgets.QPushButton(parent=self.page_vulner)
        self.btn_openVulner.setGeometry(QtCore.QRect(780, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_openVulner.setFont(font)
        self.btn_openVulner.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_openVulner.setIcon(icon3)
        self.btn_openVulner.setIconSize(QtCore.QSize(30, 30))
        self.btn_openVulner.setObjectName("btn_openVulner")
        self.btn_scanVulner = QtWidgets.QPushButton(parent=self.page_vulner)
        self.btn_scanVulner.setGeometry(QtCore.QRect(610, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_scanVulner.setFont(font)
        self.btn_scanVulner.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_scanVulner.setIcon(icon7)
        self.btn_scanVulner.setIconSize(QtCore.QSize(30, 30))
        self.btn_scanVulner.setObjectName("btn_scanVulner")
        self.lineEdit_inputVulner = QtWidgets.QLineEdit(parent=self.page_vulner)
        self.lineEdit_inputVulner.setGeometry(QtCore.QRect(350, 100, 811, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_inputVulner.setFont(font)
        self.lineEdit_inputVulner.setStyleSheet("QLineEdit {\n"
"  border: 1px solid gray;\n"
"  color: rgba(40,43,61,255);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid;\n"
"  border-color: rgba(0,143,255,255);\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid;\n"
"  border-color: rgba(88,199,141,255);\n"
"}\n"
"")
        self.lineEdit_inputVulner.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_inputVulner.setObjectName("lineEdit_inputVulner")
        self.btn_stealth = QtWidgets.QPushButton(parent=self.page_vulner)
        self.btn_stealth.setGeometry(QtCore.QRect(470, 240, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stealth.setFont(font)
        self.btn_stealth.setStyleSheet("QPushButton{\n"
"         border: 1px solid gray;\n"
"          color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"QPushButton:focus {\n"
"  border: 1px solid;\n"
"  border-color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_stealth.setObjectName("btn_stealth")
        self.btn_agressive = QtWidgets.QPushButton(parent=self.page_vulner)
        self.btn_agressive.setGeometry(QtCore.QRect(640, 240, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_agressive.setFont(font)
        self.btn_agressive.setStyleSheet("QPushButton{\n"
"         border: 1px solid gray;\n"
"          color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"QPushButton:focus {\n"
"  border: 1px solid;\n"
"  border-color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_agressive.setObjectName("btn_agressive")
        self.btn_adaptive = QtWidgets.QPushButton(parent=self.page_vulner)
        self.btn_adaptive.setGeometry(QtCore.QRect(830, 240, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_adaptive.setFont(font)
        self.btn_adaptive.setStyleSheet("QPushButton{\n"
"         border: 1px solid gray;\n"
"          color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"QPushButton:focus {\n"
"  border: 1px solid;\n"
"  border-color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_adaptive.setObjectName("btn_adaptive")
        self.btn_nse = QtWidgets.QPushButton(parent=self.page_vulner)
        self.btn_nse.setGeometry(QtCore.QRect(990, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_nse.setFont(font)
        self.btn_nse.setStyleSheet("QPushButton{\n"
"         border: 1px solid gray;\n"
"          color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"    border: 1px solid;\n"
"   border-color:  rgba(0,143,255,255);\n"
"}\n"
"QPushButton:focus {\n"
"  border: 1px solid;\n"
"  border-color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_nse.setObjectName("btn_nse")
        self.widget_outputVulner = QtWidgets.QWidget(parent=self.page_vulner)
        self.widget_outputVulner.setGeometry(QtCore.QRect(300, 300, 931, 371))
        self.widget_outputVulner.setStyleSheet("background-color:rgba(242,243,245,255);\n"
"border-radius: 5px;")
        self.widget_outputVulner.setObjectName("widget_outputVulner")
        self.btn_moreVulner = QtWidgets.QPushButton(parent=self.widget_outputVulner)
        self.btn_moreVulner.setGeometry(QtCore.QRect(770, 320, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_moreVulner.setFont(font)
        self.btn_moreVulner.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_moreVulner.setIcon(icon6)
        self.btn_moreVulner.setIconSize(QtCore.QSize(30, 30))
        self.btn_moreVulner.setObjectName("btn_moreVulner")
        self.btn_backVulner = QtWidgets.QPushButton(parent=self.page_vulner)
        self.btn_backVulner.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backVulner.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backVulner.setText("")
        self.btn_backVulner.setIcon(icon2)
        self.btn_backVulner.setIconSize(QtCore.QSize(30, 30))
        self.btn_backVulner.setObjectName("btn_backVulner")
        self.stackedWidget.addWidget(self.page_vulner)
        self.page_detailVulner = QtWidgets.QWidget()
        self.page_detailVulner.setObjectName("page_detailVulner")
        self.label_7 = QtWidgets.QLabel(parent=self.page_detailVulner)
        self.label_7.setGeometry(QtCore.QRect(640, 290, 55, 16))
        self.label_7.setObjectName("label_7")
        self.btn_backDetailVulner = QtWidgets.QPushButton(parent=self.page_detailVulner)
        self.btn_backDetailVulner.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backDetailVulner.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backDetailVulner.setText("")
        self.btn_backDetailVulner.setIcon(icon2)
        self.btn_backDetailVulner.setIconSize(QtCore.QSize(30, 30))
        self.btn_backDetailVulner.setObjectName("btn_backDetailVulner")
        self.stackedWidget.addWidget(self.page_detailVulner)
        self.page_https = QtWidgets.QWidget()
        self.page_https.setObjectName("page_https")
        self.label_https = QtWidgets.QLabel(parent=self.page_https)
        self.label_https.setGeometry(QtCore.QRect(660, 50, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_https.setFont(font)
        self.label_https.setStyleSheet("color: rgb(38, 50, 56);")
        self.label_https.setObjectName("label_https")
        self.lineEdit_inputHttps = QtWidgets.QLineEdit(parent=self.page_https)
        self.lineEdit_inputHttps.setGeometry(QtCore.QRect(340, 110, 811, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_inputHttps.setFont(font)
        self.lineEdit_inputHttps.setStyleSheet("QLineEdit {\n"
"  border: 1px solid gray;\n"
"  color: rgba(40,43,61,255);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid;\n"
"  border-color: rgba(0,143,255,255);\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid;\n"
"  border-color: rgba(88,199,141,255);\n"
"}\n"
"")
        self.lineEdit_inputHttps.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_inputHttps.setObjectName("lineEdit_inputHttps")
        self.btn_openHttps = QtWidgets.QPushButton(parent=self.page_https)
        self.btn_openHttps.setGeometry(QtCore.QRect(830, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_openHttps.setFont(font)
        self.btn_openHttps.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_openHttps.setIcon(icon3)
        self.btn_openHttps.setIconSize(QtCore.QSize(30, 30))
        self.btn_openHttps.setObjectName("btn_openHttps")
        self.btn_scanHttps = QtWidgets.QPushButton(parent=self.page_https)
        self.btn_scanHttps.setGeometry(QtCore.QRect(620, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_scanHttps.setFont(font)
        self.btn_scanHttps.setStyleSheet(" QPushButton{\n"
"        background-color: rgba(50,54,74,255);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_scanHttps.setIcon(icon7)
        self.btn_scanHttps.setIconSize(QtCore.QSize(30, 30))
        self.btn_scanHttps.setObjectName("btn_scanHttps")
        self.widget_outputHttps = QtWidgets.QWidget(parent=self.page_https)
        self.widget_outputHttps.setGeometry(QtCore.QRect(270, 270, 991, 371))
        self.widget_outputHttps.setStyleSheet("background-color:rgba(242,243,245,255);\n"
"border-radius: 5px;")
        self.widget_outputHttps.setObjectName("widget_outputHttps")
        self.label_preloadHttps = QtWidgets.QLabel(parent=self.widget_outputHttps)
        self.label_preloadHttps.setGeometry(QtCore.QRect(40, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_preloadHttps.setFont(font)
        self.label_preloadHttps.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_preloadHttps.setObjectName("label_preloadHttps")
        self.label_certificateHttps = QtWidgets.QLabel(parent=self.widget_outputHttps)
        self.label_certificateHttps.setGeometry(QtCore.QRect(40, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_certificateHttps.setFont(font)
        self.label_certificateHttps.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_certificateHttps.setObjectName("label_certificateHttps")
        self.label_dateHttps = QtWidgets.QLabel(parent=self.widget_outputHttps)
        self.label_dateHttps.setGeometry(QtCore.QRect(40, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_dateHttps.setFont(font)
        self.label_dateHttps.setStyleSheet("color: rgb(42, 49, 66);\n"
" background-color: transparent; \n"
"   \n"
"")
        self.label_dateHttps.setObjectName("label_dateHttps")
        self.btn_moreHttps = QtWidgets.QPushButton(parent=self.widget_outputHttps)
        self.btn_moreHttps.setGeometry(QtCore.QRect(830, 320, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_moreHttps.setFont(font)
        self.btn_moreHttps.setStyleSheet(" QPushButton{\n"
"        background-color: rgb(42, 49, 66);\n"
"        border-radius: 5px;\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"     background-color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_moreHttps.setIcon(icon6)
        self.btn_moreHttps.setIconSize(QtCore.QSize(30, 30))
        self.btn_moreHttps.setObjectName("btn_moreHttps")
        self.btn_backHttps = QtWidgets.QPushButton(parent=self.page_https)
        self.btn_backHttps.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backHttps.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backHttps.setText("")
        self.btn_backHttps.setIcon(icon2)
        self.btn_backHttps.setIconSize(QtCore.QSize(30, 30))
        self.btn_backHttps.setObjectName("btn_backHttps")
        self.stackedWidget.addWidget(self.page_https)
        self.page_detailHttps = QtWidgets.QWidget()
        self.page_detailHttps.setObjectName("page_detailHttps")
        self.label_8 = QtWidgets.QLabel(parent=self.page_detailHttps)
        self.label_8.setGeometry(QtCore.QRect(700, 310, 55, 16))
        self.label_8.setObjectName("label_8")
        self.btn_backDetailHttps = QtWidgets.QPushButton(parent=self.page_detailHttps)
        self.btn_backDetailHttps.setGeometry(QtCore.QRect(200, 30, 93, 31))
        self.btn_backDetailHttps.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"    }")
        self.btn_backDetailHttps.setText("")
        self.btn_backDetailHttps.setIcon(icon2)
        self.btn_backDetailHttps.setIconSize(QtCore.QSize(30, 30))
        self.btn_backDetailHttps.setObjectName("btn_backDetailHttps")
        self.stackedWidget.addWidget(self.page_detailHttps)
        self.page_aboutUs = QtWidgets.QWidget()
        self.page_aboutUs.setObjectName("page_aboutUs")
        self.label_9 = QtWidgets.QLabel(parent=self.page_aboutUs)
        self.label_9.setGeometry(QtCore.QRect(720, 310, 55, 16))
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_aboutUs)
        self.widget_left = QtWidgets.QWidget(parent=Form)
        self.widget_left.setGeometry(QtCore.QRect(0, 0, 211, 741))
        self.widget_left.setObjectName("widget_left")
        self.btn_home = QtWidgets.QPushButton(parent=self.widget_left)
        self.btn_home.setGeometry(QtCore.QRect(30, 170, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"        color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"    color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_home.setObjectName("btn_home")
        self.btn_advancedUserLeft = QtWidgets.QPushButton(parent=self.widget_left)
        self.btn_advancedUserLeft.setGeometry(QtCore.QRect(20, 220, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_advancedUserLeft.setFont(font)
        self.btn_advancedUserLeft.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"        color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"    color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_advancedUserLeft.setObjectName("btn_advancedUserLeft")
        self.btn_networkUserTop = QtWidgets.QPushButton(parent=self.widget_left)
        self.btn_networkUserTop.setGeometry(QtCore.QRect(20, 270, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_networkUserTop.setFont(font)
        self.btn_networkUserTop.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"        color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"    color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_networkUserTop.setObjectName("btn_networkUserTop")
        self.btn_aboutUs = QtWidgets.QPushButton(parent=self.widget_left)
        self.btn_aboutUs.setGeometry(QtCore.QRect(20, 690, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_aboutUs.setFont(font)
        self.btn_aboutUs.setStyleSheet(" QPushButton{\n"
"        border-radius: 5px;\n"
"        color: rgb(42, 49, 66);\n"
"    }\n"
" QPushButton{\n"
"        border-radius: 10px;\n"
"    }\n"
"QPushButton:hover {\n"
"     border-radius: 10px;\n"
"    color: rgba(0,143,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color:  rgba(0,143,255,255);\n"
"}\n"
"")
        self.btn_aboutUs.setObjectName("btn_aboutUs")
        self.label_gizmo = QtWidgets.QLabel(parent=self.widget_left)
        self.label_gizmo.setGeometry(QtCore.QRect(20, 10, 161, 131))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_gizmo.setFont(font)
        self.label_gizmo.setStyleSheet("color: rgb(42, 49, 66);")
        self.label_gizmo.setText("")
        self.label_gizmo.setPixmap(QtGui.QPixmap("d:\\ISAN Security Gizmo Box\\assets\\ui\\../icons/logo.png"))
        self.label_gizmo.setScaledContents(True)
        self.label_gizmo.setObjectName("label_gizmo")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labe_isanSec.setText(_translate("Form", "ISAN SECURITY "))
        self.label_description1Home.setText(_translate("Form", "The ISAN security gizmo box is a security device or software suite"))
        self.label_description2Home.setText(_translate("Form", " that offers five different tools for various security purposes."))
        self.btn_advancedUserHome.setText(_translate("Form", "ADVANCED USER"))
        self.btn_networkUserHome.setText(_translate("Form", "NETWORK ENGINEER"))
        self.label_gizmoHome.setText(_translate("Form", "GIZMO BOX"))
        self.btn_password.setText(_translate("Form", "PASSWORD EVALUATUON"))
        self.btn_malware.setText(_translate("Form", "MALWARE SCANNING"))
        self.btn_digest.setText(_translate("Form", "MESSAGE DIGEST"))
        self.label_isanSec_adupage.setText(_translate("Form", "ISAN SECURITY GIZMO BOX"))
        self.label_advancdUser.setText(_translate("Form", " ADVANCED USER"))
        self.label_description_adupage.setText(_translate("Form", "Advanced user tools include password evaluation, malware scanning, message digest."))
        self.lineEdit_inputPwd.setPlaceholderText(_translate("Form", "TYPE HERE"))
        self.label_pwd.setText(_translate("Form", "PASSWORD EVALUATION"))
        self.label_title_specialWarning.setText(_translate("Form", "SPECIAL WARINING!"))
        self.checkDigits.setText(_translate("Form", "DIGITS"))
        self.checkLower.setText(_translate("Form", "LOWER CASE LATIN LETTERS"))
        self.checkUpper.setText(_translate("Form", "UPPER CASE LATIN LETTERS"))
        self.checkSpecial.setText(_translate("Form", "SPECIAL CHARACTERS"))
        self.checkLength.setText(_translate("Form", "LENGTH >= 8"))
        self.label_pwdStrength.setText(_translate("Form", "YOUR PASSWORD STRENGTH"))
        self.label_timetocrack.setText(_translate("Form", "ESTIMATED TIME TO CRACK"))
        self.label_entropy.setText(_translate("Form", "PASSWORD ENTROPY"))
        self.label_chkNordpass.setText(_translate("Form", "SEARCH FOR YOUT PASSWORD IN THE NORDPASS WORDLISTS"))
        self.btn_dicattack.setText(_translate("Form", "DICTIONARY ATTACK"))
        self.label_outStrengthPwd.setText(_translate("Form", "--"))
        self.label_outTimeCrackPwd.setText(_translate("Form", "--"))
        self.label_outEntropyPwd.setText(_translate("Form", "--"))
        self.label_outChkNordpass.setText(_translate("Form", "--"))
        self.label_textPwd.setText(_translate("Form", "THIS WILL NOT BE SENT ANYWARE."))
        self.label_dictionary.setText(_translate("Form", "DICTIONART ATTACK"))
        self.lineEdit_inputDic.setPlaceholderText(_translate("Form", "TYPE HERE"))
        self.label_textPwd2.setText(_translate("Form", "THIS WILL NOT BE SENT ANYWARE."))
        self.label_outDic.setText(_translate("Form", "--"))
        self.btn_openDic.setText(_translate("Form", "OPEN"))
        self.btn_rockyou.setText(_translate("Form", "ROCKYOU.TXT"))
        self.btn_crackstation.setText(_translate("Form", "CRACKSTATION.TXT"))
        self.lineEdit_inputFileDic.setPlaceholderText(_translate("Form", "ONLY TEXT FILE"))
        self.btn_clearDic.setText(_translate("Form", "CLEAR"))
        self.label_malware.setText(_translate("Form", "MALWARE SCANNING"))
        self.lineEdit_inputMalware.setPlaceholderText(_translate("Form", "TYPE HERE"))
        self.label_nameMalware.setText(_translate("Form", "NAME"))
        self.label_sizeMalware.setText(_translate("Form", "SIZE"))
        self.label_dateMalware.setText(_translate("Form", "DATE"))
        self.label_typeMalware.setText(_translate("Form", "TYPE"))
        self.btn_moreMalware.setText(_translate("Form", "READ MORE"))
        self.btn_clearMalware.setText(_translate("Form", "CLEAR"))
        self.btn_scanMalware.setText(_translate("Form", "SCAN"))
        self.btn_openMalware.setText(_translate("Form", "OPEN"))
        self.label_5.setText(_translate("Form", "Detail malware"))
        self.label_digest.setText(_translate("Form", "MESSAGE DIGEST"))
        self.lineEdit_inputDigest.setPlaceholderText(_translate("Form", "TYPE HERE"))
        self.btn_openDigest.setText(_translate("Form", "OPEN"))
        self.btn_clearDigest.setText(_translate("Form", "CLEAR"))
        self.comboBox_sha2.setItemText(0, _translate("Form", "SHA-2"))
        self.comboBox_sha2.setItemText(1, _translate("Form", "224 BIT"))
        self.comboBox_sha2.setItemText(2, _translate("Form", "256 BIT"))
        self.comboBox_sha2.setItemText(3, _translate("Form", "384 BIT"))
        self.comboBox_sha2.setItemText(4, _translate("Form", "512 BIT"))
        self.btn_md5.setText(_translate("Form", "MD5"))
        self.btn_sha1.setText(_translate("Form", "SHA-1"))
        self.comboBox_sha3.setItemText(0, _translate("Form", "SHA-3"))
        self.comboBox_sha3.setItemText(1, _translate("Form", "224 BIT"))
        self.comboBox_sha3.setItemText(2, _translate("Form", "256 BIT"))
        self.comboBox_sha3.setItemText(3, _translate("Form", "384 BIT"))
        self.comboBox_sha3.setItemText(4, _translate("Form", "512 BIT"))
        self.label_resultDigest.setText(_translate("Form", "RESULT"))
        self.btn_saveDigest.setText(_translate("Form", "SAVE"))
        self.label_outDic_3.setText(_translate("Form", "--"))
        self.label_isanSec_nwu.setText(_translate("Form", "ISAN SECURITY GIZMO BOX"))
        self.btn_vulner.setText(_translate("Form", "VULNERABILITY SCANNING"))
        self.label_networkUser.setText(_translate("Form", "NETWORK ENGINEER"))
        self.label_description_nwu.setText(_translate("Form", "Network engineer tools include Vulnerability Scanning, HTTPS Testing."))
        self.btn_https.setText(_translate("Form", "HTTPS TESTING"))
        self.label_vulner.setText(_translate("Form", "VULNERABILITY SCANNING"))
        self.btn_openVulner.setText(_translate("Form", "OPEN"))
        self.btn_scanVulner.setText(_translate("Form", "SCAN"))
        self.lineEdit_inputVulner.setPlaceholderText(_translate("Form", "TYPE HERE"))
        self.btn_stealth.setText(_translate("Form", "STEALTH"))
        self.btn_agressive.setText(_translate("Form", "AGRESSIVE"))
        self.btn_adaptive.setText(_translate("Form", "ADAPTIVE"))
        self.btn_nse.setText(_translate("Form", "VULNER.NSE"))
        self.btn_moreVulner.setText(_translate("Form", "READ MORE"))
        self.label_7.setText(_translate("Form", "Deatil Vulner"))
        self.label_https.setText(_translate("Form", "HTTPS TESTING"))
        self.lineEdit_inputHttps.setPlaceholderText(_translate("Form", "TYPE HERE"))
        self.btn_openHttps.setText(_translate("Form", "OPEN"))
        self.btn_scanHttps.setText(_translate("Form", "SCAN"))
        self.label_preloadHttps.setText(_translate("Form", "HSTS PRELOAD"))
        self.label_certificateHttps.setText(_translate("Form", "CERTIFICATE"))
        self.label_dateHttps.setText(_translate("Form", "DATE"))
        self.btn_moreHttps.setText(_translate("Form", "READ MORE"))
        self.label_8.setText(_translate("Form", "detail https"))
        self.label_9.setText(_translate("Form", "about us"))
        self.btn_home.setText(_translate("Form", "HOME"))
        self.btn_advancedUserLeft.setText(_translate("Form", "ADVANCED USER"))
        self.btn_networkUserTop.setText(_translate("Form", "NETWORK ENGINEER"))
        self.btn_aboutUs.setText(_translate("Form", "ABOUT US"))
